# Generated by Django 5.1.11 on 2026-02-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("master", "Master"),
                    ("manager", "Manager"),
                    ("gold", "Gold"),
                    ("regular", "Regular"),
                ],
                default="regular",
                max_length=10,
            ),
        ),
    ]
