# Generated by Django 5.1.11 on 2026-02-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="deletion_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
