# Generated by Django 5.1.11 on 2026-02-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_notificationratelimit_devicetoken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetoken",
            name="language",
            field=models.CharField(default="en", max_length=10),
        ),
    ]
