# Generated by Django 5.1.11 on 2026-04-26 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_notificationhistory_post_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionInfo",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="subscription",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revenuecat_app_user_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("product_id", models.CharField(blank=True, max_length=100)),
                ("store", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=False)),
                ("original_purchase_date", models.DateTimeField(blank=True, null=True)),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                (
                    "unsubscribe_detected_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_trial", models.BooleanField(default=False)),
                ("has_used_trial", models.BooleanField(default=False)),
                ("trial_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_webhook_event", models.CharField(blank=True, max_length=50)),
                ("last_webhook_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "accounts_subscription_info",
            },
        ),
    ]
