# Generated by Django 5.1.11 on 2026-05-25 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_subscriptioninfo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="investment_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "investment_style",
                    models.CharField(
                        choices=[
                            ("conservative", "Conservative"),
                            ("balanced", "Balanced"),
                            ("aggressive", "Aggressive"),
                        ],
                        default="balanced",
                        max_length=15,
                    ),
                ),
                (
                    "time_horizon",
                    models.CharField(
                        choices=[
                            ("short", "Short-term (< 1 year)"),
                            ("medium", "Medium-term (1-5 years)"),
                            ("long", "Long-term (5+ years)"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("risk_tolerance", models.IntegerField(default=3)),
                (
                    "target_return",
                    models.IntegerField(
                        choices=[(5, "5%"), (10, "10%"), (20, "20%"), (0, "Flexible")],
                        default=10,
                    ),
                ),
                (
                    "max_loss_tolerance",
                    models.IntegerField(
                        choices=[
                            (-5, "-5%"),
                            (-10, "-10%"),
                            (-20, "-20%"),
                            (-40, "-40%"),
                            (-100, "Unlimited"),
                        ],
                        default=-20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "accounts_investment_profile",
            },
        ),
    ]
