# Generated by Django 5.1.11 on 2026-06-03 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_investmentprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("rank", models.IntegerField()),
                ("ticker", models.CharField(max_length=20)),
                ("fit_score", models.FloatField()),
                ("rationale_json", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                ("name_ko", models.CharField(blank=True, default="", max_length=128)),
                ("current_price", models.FloatField(blank=True, null=True)),
                ("change_pct", models.FloatField(blank=True, null=True)),
                ("signal", models.CharField(blank=True, default="", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "accounts_recommendation",
                "ordering": ["rank"],
            },
        ),
        migrations.RenameIndex(
            model_name="customuser",
            new_name="accounts_us_email_74c8d6_idx",
            old_name="users_email_4b85f2_idx",
        ),
        migrations.RenameIndex(
            model_name="customuser",
            new_name="accounts_us_created_4734df_idx",
            old_name="users_created_6541e9_idx",
        ),
        migrations.RenameIndex(
            model_name="emailverificationcode",
            new_name="accounts_em_email_7bc994_idx",
            old_name="accounts_em_email_purpose_idx",
        ),
        migrations.AddField(
            model_name="recommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "date", "rank"], name="accounts_re_user_id_7645cf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recommendation",
            unique_together={("user", "date", "ticker")},
        ),
    ]
