# Generated by Django 5.1.11 on 2025-11-02 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Hashtag",
                "verbose_name_plural": "Hashtags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                (
                    "native_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EN", "🇺🇸 English"),
                            ("KO", "🇰🇷 한국어"),
                            ("JA", "🇯🇵 日本語"),
                            ("ZH", "🇨🇳 中文"),
                            ("ES", "🇪🇸 Español"),
                            ("FR", "🇫🇷 Français"),
                            ("DE", "🇩🇪 Deutsch"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EN", "🇺🇸 English"),
                            ("KO", "🇰🇷 한국어"),
                            ("JA", "🇯🇵 日本語"),
                            ("ZH", "🇨🇳 中文"),
                            ("ES", "🇪🇸 Español"),
                            ("FR", "🇫🇷 Français"),
                            ("DE", "🇩🇪 Deutsch"),
                        ],
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hashtags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="posts.hashtag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-created_at"],
            },
        ),
    ]
