# Generated by Django 5.1.11 on 2025-11-16 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_postfavorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("abuse", "욕설/비방"),
                            ("spam", "스팸/광고"),
                            ("inappropriate", "부적절한 내용"),
                            ("harassment", "성희롱"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                        verbose_name="Report Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("reviewing", "검토 중"),
                            ("resolved", "처리 완료"),
                            ("dismissed", "기각"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                ("admin_note", models.TextField(blank=True, verbose_name="Admin Note")),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="posts.post",
                        verbose_name="Post",
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_reports_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reported User",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_reports_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reporter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Report",
                "verbose_name_plural": "Post Reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="posts_postr_status_02a33f_idx",
                    ),
                    models.Index(
                        fields=["reported_user", "status"],
                        name="posts_postr_reporte_ad8d72_idx",
                    ),
                ],
            },
        ),
    ]
