# Generated by Django 5.1.11 on 2025-11-16 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_postreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="삭제 시각"),
        ),
        migrations.AddField(
            model_name="post",
            name="deletion_reason",
            field=models.CharField(blank=True, max_length=20, verbose_name="삭제 사유"),
        ),
        migrations.AddField(
            model_name="post",
            name="is_deleted_by_report",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="신고로 삭제됨"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="original_content",
            field=models.TextField(
                blank=True,
                help_text="삭제 전 원본 보존 (관리자 전용)",
                max_length=1000,
                verbose_name="원본 내용",
            ),
        ),
        migrations.AddField(
            model_name="postreport",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_resolved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="처리한 관리자",
            ),
        ),
    ]
