# Generated by Django 5.1.11 on 2025-11-16 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_post_deleted_at_post_deletion_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="postreport",
            index=models.Index(
                fields=["report_type", "created_at"],
                name="posts_postr_report__322694_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postreport",
            index=models.Index(
                fields=["reporter", "status"], name="posts_postr_reporte_3de973_idx"
            ),
        ),
    ]
