# Generated by Django 5.1.11 on 2025-11-16 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_postreport_posts_postr_report__322694_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="deletion_reason",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="is_deleted_by_report",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="original_content",
            field=models.TextField(
                blank=True, help_text="Original content before deletion", null=True
            ),
        ),
        migrations.CreateModel(
            name="CommentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("abuse", "욕설/비방"),
                            ("spam", "스팸/광고"),
                            ("inappropriate", "부적절한 내용"),
                            ("harassment", "성희롱"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                        verbose_name="신고 유형",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="상세 내용"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("reviewing", "검토 중"),
                            ("resolved", "처리 완료"),
                            ("dismissed", "기각"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="처리 상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="신고 시간"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="검토 시간"
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, null=True, verbose_name="관리자 메모"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="posts.comment",
                        verbose_name="신고된 댓글",
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_reports_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="피신고자",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_reports_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신고자",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comment_reports_resolved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="처리한 관리자",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment Report",
                "verbose_name_plural": "Comment Reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="posts_comme_status_27f7f1_idx",
                    ),
                    models.Index(
                        fields=["reported_user", "status"],
                        name="posts_comme_reporte_1684f0_idx",
                    ),
                    models.Index(
                        fields=["report_type", "created_at"],
                        name="posts_comme_report__c9d5d2_idx",
                    ),
                    models.Index(
                        fields=["reporter", "status"],
                        name="posts_comme_reporte_a73379_idx",
                    ),
                ],
            },
        ),
    ]
