# Generated by Django 5.1.11 on 2025-12-01 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_comment_deleted_at_comment_deletion_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("click", "Click"),
                            ("like", "Like"),
                            ("unlike", "Unlike"),
                            ("comment", "Comment"),
                            ("share", "Share"),
                            ("favorite", "Favorite"),
                            ("skip", "Skip"),
                            ("report", "Report"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Interaction Type",
                    ),
                ),
                (
                    "scroll_depth",
                    models.IntegerField(
                        default=0,
                        help_text="How far user scrolled in post (0-100%)",
                        verbose_name="Scroll Depth (%)",
                    ),
                ),
                (
                    "dwell_time",
                    models.FloatField(
                        default=0.0,
                        help_text="Time spent viewing post",
                        verbose_name="Dwell Time (seconds)",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context: device, feed_position, source_feed, etc.",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="posts.post",
                        verbose_name="Post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_interactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Interaction",
                "verbose_name_plural": "User Interactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "interaction_type", "-created_at"],
                        name="posts_useri_user_id_1b6935_idx",
                    ),
                    models.Index(
                        fields=["post", "interaction_type", "-created_at"],
                        name="posts_useri_post_id_8bb12a_idx",
                    ),
                    models.Index(
                        fields=["user", "post", "-created_at"],
                        name="posts_useri_user_id_306fb8_idx",
                    ),
                    models.Index(
                        fields=["interaction_type", "-created_at"],
                        name="posts_useri_interac_b5e12f_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="posts_useri_created_ce65a9_idx"
                    ),
                ],
            },
        ),
    ]
