# Generated by Django 5.1.11 on 2026-02-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_post_deleted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="ticker",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
