# Generated by Django 5.1.11 on 2025-10-12 10:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="구독 플랜 이름", max_length=100)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("monthly", "월간 구독"),
                            ("quarterly", "분기 구독"),
                            ("yearly", "연간 구독"),
                        ],
                        help_text="구독 유형",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="가격", max_digits=10
                    ),
                ),
                ("duration_days", models.IntegerField(help_text="구독 기간 (일)")),
                (
                    "is_ad_free",
                    models.BooleanField(default=True, help_text="광고 제거"),
                ),
                (
                    "unlimited_matches",
                    models.BooleanField(default=True, help_text="무제한 매칭"),
                ),
                (
                    "priority_matching",
                    models.BooleanField(default=False, help_text="우선 매칭"),
                ),
                (
                    "profile_boost",
                    models.BooleanField(default=False, help_text="프로필 부스트"),
                ),
                (
                    "custom_badge",
                    models.BooleanField(default=False, help_text="커스텀 뱃지"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="활성화 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "구독 플랜",
                "verbose_name_plural": "구독 플랜 목록",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advertiser_name",
                    models.CharField(help_text="광고주 이름", max_length=100),
                ),
                (
                    "advertiser_email",
                    models.EmailField(help_text="광고주 이메일", max_length=254),
                ),
                ("title", models.CharField(help_text="광고 제목", max_length=200)),
                (
                    "description",
                    models.TextField(help_text="광고 설명", max_length=500),
                ),
                (
                    "ad_type",
                    models.CharField(
                        choices=[
                            ("banner", "배너 광고"),
                            ("video", "비디오 광고"),
                            ("native", "네이티브 광고"),
                        ],
                        default="banner",
                        help_text="광고 타입",
                        max_length=20,
                    ),
                ),
                ("image_url", models.URLField(blank=True, help_text="이미지 URL")),
                ("video_url", models.URLField(blank=True, help_text="비디오 URL")),
                ("link_url", models.URLField(help_text="랜딩 페이지 URL")),
                ("start_date", models.DateTimeField(help_text="시작일")),
                ("end_date", models.DateTimeField(help_text="종료일")),
                (
                    "target_countries",
                    models.JSONField(
                        default=list,
                        help_text="타겟 국가 코드 리스트 (예: ['KOR', 'USA'])",
                    ),
                ),
                (
                    "target_age_min",
                    models.IntegerField(blank=True, help_text="최소 연령", null=True),
                ),
                (
                    "target_age_max",
                    models.IntegerField(blank=True, help_text="최대 연령", null=True),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, help_text="예산", max_digits=10
                    ),
                ),
                (
                    "cost_per_click",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.1,
                        help_text="클릭당 비용 (CPC)",
                        max_digits=6,
                    ),
                ),
                (
                    "total_impressions",
                    models.IntegerField(default=0, help_text="총 노출 수"),
                ),
                (
                    "total_clicks",
                    models.IntegerField(default=0, help_text="총 클릭 수"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "활성"),
                            ("paused", "일시정지"),
                            ("ended", "종료"),
                        ],
                        default="active",
                        help_text="광고 상태",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "광고",
                "verbose_name_plural": "광고 목록",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="premium_adv_status_ad5586_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="premium_adv_start_d_311b51_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="시작일"
                    ),
                ),
                ("end_date", models.DateTimeField(help_text="종료일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "활성"),
                            ("expired", "만료"),
                            ("cancelled", "취소"),
                        ],
                        default="active",
                        help_text="구독 상태",
                        max_length=20,
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(default=False, help_text="자동 갱신 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="구독 플랜",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_subscriptions",
                        to="premium.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="구독 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 구독",
                "verbose_name_plural": "사용자 구독 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "신용/체크카드"),
                            ("bank_transfer", "계좌이체"),
                            ("mobile", "휴대폰 결제"),
                            ("kakaopay", "카카오페이"),
                            ("toss", "토스"),
                        ],
                        help_text="결제 수단",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="결제 금액", max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="KRW", help_text="통화", max_length=3),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                            ("refunded", "환불"),
                        ],
                        default="pending",
                        help_text="결제 상태",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        help_text="결제 트랜잭션 ID", max_length=100, unique=True
                    ),
                ),
                (
                    "pg_provider",
                    models.CharField(
                        blank=True, help_text="PG사 (예: toss, stripe)", max_length=50
                    ),
                ),
                ("receipt_url", models.URLField(blank=True, help_text="영수증 URL")),
                (
                    "refunded_at",
                    models.DateTimeField(blank=True, help_text="환불 시간", null=True),
                ),
                (
                    "refund_reason",
                    models.TextField(blank=True, help_text="환불 사유", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="결제자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_subscription",
                    models.ForeignKey(
                        blank=True,
                        help_text="연관된 구독",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="premium.usersubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "결제 내역",
                "verbose_name_plural": "결제 내역 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[("impression", "노출"), ("click", "클릭")],
                        help_text="액션 타입",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_impressions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "advertisement",
                    models.ForeignKey(
                        help_text="광고",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impressions",
                        to="premium.advertisement",
                    ),
                ),
            ],
            options={
                "verbose_name": "광고 노출 기록",
                "verbose_name_plural": "광고 노출 기록 목록",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["advertisement", "-created_at"],
                        name="premium_adi_adverti_af2ce8_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="premium_adi_user_id_3985f4_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["user", "status"], name="premium_use_user_id_76cadc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["end_date", "status"], name="premium_use_end_dat_283ee8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "-created_at"], name="premium_pay_user_id_7ee3db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "-created_at"], name="premium_pay_status_55b7c7_idx"
            ),
        ),
    ]
