-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgzhf5rAwQFWH9ikSi
AG86Stfc3/COoaQ0B1oc+yZ+GgGgCgYIKoZIzj0DAQehRANCAASJX9XEgc6ZVMc5
2JHYqwWjSTrirpTHKmbPvApIsnvQhen9ucAefuWc8NYTcS9661Wx+StWwwbCjGNE
8jpdnkgo
-----END PRIVATE KEY-----