# Generated by Django 5.1.11 on 2026-02-09 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("community", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "스팸"),
                            ("abuse", "욕설/비방"),
                            ("false_info", "허위 정보"),
                            ("inappropriate", "부적절한 내용"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("reviewing", "검토중"),
                            ("resolved", "처리완료"),
                            ("dismissed", "기각"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_note", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="community.comment",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "댓글 신고",
                "verbose_name_plural": "댓글 신고",
                "db_table": "comment_reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="comment_rep_status_6c15af_idx",
                    ),
                    models.Index(
                        fields=["comment"], name="comment_rep_comment_d65af4_idx"
                    ),
                ],
                "unique_together": {("comment", "reporter")},
            },
        ),
        migrations.CreateModel(
            name="PostReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "스팸"),
                            ("abuse", "욕설/비방"),
                            ("false_info", "허위 정보"),
                            ("inappropriate", "부적절한 내용"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("reviewing", "검토중"),
                            ("resolved", "처리완료"),
                            ("dismissed", "기각"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_note", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="community.post",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글 신고",
                "verbose_name_plural": "게시글 신고",
                "db_table": "post_reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="post_report_status_5f2307_idx",
                    ),
                    models.Index(
                        fields=["post"], name="post_report_post_id_7fb73b_idx"
                    ),
                ],
                "unique_together": {("post", "reporter")},
            },
        ),
    ]
