# Generated by Django 5.1.11 on 2026-06-07 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
        ("moderation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        help_text="차단당한 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        help_text="차단을 행한 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "context_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="community.comment",
                    ),
                ),
                (
                    "context_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="community.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 차단",
                "verbose_name_plural": "사용자 차단",
                "db_table": "moderation_blocked_user",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["blocker"], name="moderation__blocker_50174f_idx"
                    ),
                    models.Index(
                        fields=["blocked"], name="moderation__blocked_d789db_idx"
                    ),
                ],
                "unique_together": {("blocker", "blocked")},
            },
        ),
    ]
