"""
Django settings for hypehere project.

Generated by 'django-admin startproject' using Django 5.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Generate new secret key using:
# python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY environment variable is not set. Please set it before running the application.")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG should be False in production
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# For production, set ALLOWED_HOSTS environment variable
# Example: ALLOWED_HOSTS=example.com,www.example.com,api.example.com
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    "daphne",  # Must be at the top for Channels
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "rest_framework",
    "rest_framework.authtoken",
    "channels",
    # Local apps
    "accounts",
    "specs",
    "posts",
    "chat",
    "notifications",
    "learning",
    "analytics",  # Admin dashboard and analytics
]

# Conditionally add lotto app (only if directory exists - local development only)
import os
if os.path.exists(BASE_DIR / 'lotto'):
    INSTALLED_APPS.append("lotto")  # Lottery functionality (local only - excluded from AWS via .gitignore)

# Add django-storages only in production (when installed)
if not DEBUG:
    try:
        import storages  # noqa
        INSTALLED_APPS.append("storages")
    except ImportError:
        pass  # django-storages not installed, will use local storage

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Static file serving (must be after SecurityMiddleware)
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # Language detection and activation
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.middleware.SuspensionCheckMiddleware",  # Auto-lift expired suspensions
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "analytics.middleware.VisitorTrackingMiddleware",  # Track visitors and user activity
]

ROOT_URLCONF = "hypehere.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
            ],
        },
    },
]

WSGI_APPLICATION = "hypehere.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Environment-based database configuration
if DEBUG:
    # Development: SQLite (simple, no setup required)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    # Production: PostgreSQL (scalable, supports multiple instances)
    # Requires DATABASE_URL environment variable
    # Format: postgresql://user:password@host:5432/dbname
    import dj_database_url

    database_url = os.environ.get('DATABASE_URL')
    if not database_url:
        raise ValueError("DATABASE_URL environment variable must be set in production (DEBUG=False)")

    DATABASES = {
        "default": dj_database_url.config(
            default=database_url,
            conn_max_age=600,  # Connection pooling: reuse connections for 10 minutes
            conn_health_checks=True,  # Check connection health before reuse
        )
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ko"

from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('ko', _('한국어')),
    ('en', _('English')),
    ('ja', _('日本語')),
    ('es', _('Español')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Static files collection directory (required for production)
# Run 'python manage.py collectstatic' before deployment
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = "accounts.User"

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django Channels
ASGI_APPLICATION = 'hypehere.asgi.application'

# Channel Layers (for WebSocket)
if DEBUG:
    # Development: In-memory channel layer (simple, no Redis needed)
    # Note: Only works with single server instance
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer'
        },
    }
else:
    # Production: Redis channel layer for AWS with TLS/SSL support
    # Parse Redis URL from environment
    redis_url = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')

    # Convert redis:// to rediss:// for TLS
    if redis_url.startswith('redis://'):
        redis_url_tls = redis_url.replace('redis://', 'rediss://', 1)
    else:
        redis_url_tls = redis_url

    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                # Use rediss:// protocol for TLS connection
                # AWS ElastiCache with TLS enabled requires rediss:// URL scheme
                'hosts': [redis_url_tls + '?ssl_cert_reqs=none'],
            },
        },
    }

# ==================== Email Configuration ====================

# Gmail SMTP Configuration
# For development, you can use console backend to print emails instead of sending
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production, use SMTP backend with Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Email credentials from environment variables (required in production)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

# Validation: Ensure email credentials are set in production
if not DEBUG:
    if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
        raise ValueError("EMAIL_HOST_USER and EMAIL_HOST_PASSWORD must be set in production environment.")

# Default email address to use for various automated correspondence
DEFAULT_FROM_EMAIL = f'HypeHere <{EMAIL_HOST_USER}>'
SERVER_EMAIL = f'HypeHere <{EMAIL_HOST_USER}>'

# Site URL for email links and redirects
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000')

# In production, SITE_URL should use HTTPS
if not DEBUG and SITE_URL.startswith('http://'):
    import warnings
    warnings.warn("SITE_URL should use HTTPS in production", UserWarning)

# Email Configuration Notes:
# 1. For Gmail, you need to generate an "App Password" (not your regular password)
# 2. Visit: https://myaccount.google.com/apppasswords
# 3. Enable 2-factor authentication first if not already enabled
# 4. Generate app password and use it in EMAIL_HOST_PASSWORD
# 5. For development, you can use console backend to test without actual emails

# ==================== Security Settings ====================

# Production Security Settings (only when DEBUG=False)
if not DEBUG:
    # Force HTTPS
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Session and CSRF security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token for API requests
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Additional security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

    # CSRF trusted origins (set via environment variable)
    # Example: CSRF_TRUSTED_ORIGINS=https://example.com,https://www.example.com
    csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
    if csrf_origins:
        CSRF_TRUSTED_ORIGINS = csrf_origins.split(',')

# ==================== AWS S3 Configuration (for production - Phase 3) ====================

if not DEBUG:
    # AWS S3 Settings (optional - only use if bucket is configured)
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')

    # Only use S3 if all credentials are provided
    if AWS_STORAGE_BUCKET_NAME and AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
        # S3 Configuration
        AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
        AWS_S3_OBJECT_PARAMETERS = {
            'CacheControl': 'max-age=86400',  # 1 day cache
        }
        AWS_DEFAULT_ACL = 'public-read'
        AWS_S3_FILE_OVERWRITE = False
        AWS_QUERYSTRING_AUTH = False

        # Static files (CSS, JavaScript, Images) from S3
        STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
        STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'

        # Media files (User uploads) from S3
        DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    else:
        # Fallback to WhiteNoise for static files (no S3)
        STATIC_URL = '/static/'
        STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        # Media files served locally
        MEDIA_URL = '/media/'

# Notes:
# 1. AWS credentials can be set via environment variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY)
# 2. For better security, use IAM roles instead of access keys when deploying to EC2/ECS
# 3. S3 bucket must have proper CORS configuration for file uploads
# 4. Run 'python manage.py collectstatic' before deploying to upload static files to S3
