# Generated by Django 5.1.11 on 2025-11-27 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, unique=True, verbose_name="Date"),
                ),
                (
                    "unique_visitors",
                    models.IntegerField(default=0, verbose_name="Unique Visitors"),
                ),
                (
                    "total_page_views",
                    models.IntegerField(default=0, verbose_name="Total Page Views"),
                ),
                ("new_users", models.IntegerField(default=0, verbose_name="New Users")),
                (
                    "active_users",
                    models.IntegerField(default=0, verbose_name="Active Users"),
                ),
                (
                    "posts_created",
                    models.IntegerField(default=0, verbose_name="Posts Created"),
                ),
                (
                    "comments_created",
                    models.IntegerField(default=0, verbose_name="Comments Created"),
                ),
                (
                    "anonymous_chat_users",
                    models.IntegerField(default=0, verbose_name="Anonymous Chat Users"),
                ),
                (
                    "anonymous_chat_conversations",
                    models.IntegerField(
                        default=0, verbose_name="Anonymous Chat Conversations"
                    ),
                ),
                (
                    "anonymous_chat_messages",
                    models.IntegerField(
                        default=0, verbose_name="Anonymous Chat Messages"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Daily Summary",
                "verbose_name_plural": "Daily Summaries",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="analytics_d_date_7a442d_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="AnonymousChatUsageStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, db_index=True, verbose_name="Date"
                    ),
                ),
                (
                    "conversations_started",
                    models.IntegerField(
                        default=0, verbose_name="Conversations Started"
                    ),
                ),
                (
                    "messages_sent",
                    models.IntegerField(default=0, verbose_name="Messages Sent"),
                ),
                (
                    "total_duration_seconds",
                    models.IntegerField(
                        default=0, verbose_name="Total Duration (seconds)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anonymous_chat_stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anonymous Chat Usage Stat",
                "verbose_name_plural": "Anonymous Chat Usage Stats",
                "ordering": ["-date", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["date", "-updated_at"],
                        name="analytics_a_date_ad6ce4_idx",
                    ),
                    models.Index(
                        fields=["user", "date"], name="analytics_a_user_id_587f8d_idx"
                    ),
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="DailyVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, db_index=True, verbose_name="Date"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Address")),
                (
                    "visit_count",
                    models.IntegerField(default=1, verbose_name="Visit Count"),
                ),
                (
                    "first_visit",
                    models.DateTimeField(auto_now_add=True, verbose_name="First Visit"),
                ),
                (
                    "last_visit",
                    models.DateTimeField(auto_now=True, verbose_name="Last Visit"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Visitor",
                "verbose_name_plural": "Daily Visitors",
                "ordering": ["-date", "-last_visit"],
                "indexes": [
                    models.Index(
                        fields=["date", "-last_visit"],
                        name="analytics_d_date_981d9a_idx",
                    ),
                    models.Index(
                        fields=["user", "date"], name="analytics_d_user_id_55611c_idx"
                    ),
                ],
                "unique_together": {("date", "ip_address", "user")},
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, db_index=True, verbose_name="Date"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="Last Activity"),
                ),
                (
                    "page_views",
                    models.IntegerField(default=0, verbose_name="Page Views"),
                ),
                (
                    "posts_created",
                    models.IntegerField(default=0, verbose_name="Posts Created"),
                ),
                (
                    "comments_created",
                    models.IntegerField(default=0, verbose_name="Comments Created"),
                ),
                (
                    "messages_sent",
                    models.IntegerField(default=0, verbose_name="Messages Sent"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity Log",
                "verbose_name_plural": "User Activity Logs",
                "ordering": ["-date", "-last_activity"],
                "indexes": [
                    models.Index(
                        fields=["date", "-last_activity"],
                        name="analytics_u_date_519087_idx",
                    ),
                    models.Index(
                        fields=["user", "date"], name="analytics_u_user_id_75127c_idx"
                    ),
                ],
                "unique_together": {("user", "date")},
            },
        ),
    ]
