# Generated by Django 5.1.11 on 2025-11-01 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("feature", "기능"),
                            ("design", "디자인"),
                            ("architecture", "아키텍처"),
                            ("api", "API"),
                            ("database", "데이터베이스"),
                            ("testing", "테스팅"),
                            ("deployment", "배포"),
                            ("documentation", "문서"),
                            ("bug", "버그"),
                            ("enhancement", "개선사항"),
                        ],
                        default="feature",
                        max_length=50,
                        verbose_name="카테고리",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "초안"),
                            ("review", "검토중"),
                            ("approved", "승인됨"),
                            ("implemented", "구현됨"),
                            ("deprecated", "폐기됨"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="v1.0", max_length=20, verbose_name="버전"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "개발 노트",
                "verbose_name_plural": "개발 노트",
                "ordering": ["-created_at"],
            },
        ),
    ]
