# Generated by Django 5.1.11 on 2025-11-08 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_add_conversationparticipant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="anonymous_room_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="is_anonymous",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="conversation",
            name="is_ephemeral",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AnonymousMatchingPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_gender",
                    models.CharField(
                        choices=[
                            ("any", "전체"),
                            ("male", "남성"),
                            ("female", "여성"),
                            ("other", "기타"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_country",
                    models.CharField(
                        blank=True,
                        help_text="빈 값은 전체 국가를 의미합니다",
                        max_length=100,
                    ),
                ),
                ("is_searching", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anonymous Matching Preference",
                "verbose_name_plural": "Anonymous Matching Preferences",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("abuse", "욕설/비방"),
                            ("spam", "스팸/광고"),
                            ("inappropriate", "부적절한 내용"),
                            ("harassment", "성희롱"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("reviewing", "검토 중"),
                            ("resolved", "처리 완료"),
                            ("dismissed", "기각"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_note", models.TextField(blank=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="chat.conversation",
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="chat_report_status_32cad0_idx",
                    ),
                    models.Index(
                        fields=["reported_user", "status"],
                        name="chat_report_reporte_4162bd_idx",
                    ),
                ],
            },
        ),
    ]
