# Generated by Django 5.1.11 on 2025-11-09 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_conversation_anonymous_room_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenChatParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_chat_participants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="OpenChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Room Name")),
                (
                    "country_code",
                    models.CharField(
                        db_index=True, max_length=2, verbose_name="Country Code"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("language", "언어교환"),
                            ("study", "스터디"),
                            ("culture", "문화교류"),
                            ("qa", "질문답변"),
                            ("freetalk", "자유대화"),
                        ],
                        db_index=True,
                        default="language",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(default=100, verbose_name="Max Participants"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Last Activity"
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="open_chat_rooms",
                        through="chat.OpenChatParticipant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Open Chat Room",
                "verbose_name_plural": "Open Chat Rooms",
                "ordering": ["-last_activity", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="openchatparticipant",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant_relations",
                to="chat.openchatroom",
            ),
        ),
        migrations.CreateModel(
            name="OpenChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Message Content")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_messages",
                        to="chat.openchatroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Open Chat Message",
                "verbose_name_plural": "Open Chat Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="openchatroom",
            index=models.Index(
                fields=["country_code", "-last_activity"],
                name="chat_opench_country_b4cec6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="openchatroom",
            index=models.Index(
                fields=["category", "-last_activity"],
                name="chat_opench_categor_5b158c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="openchatroom",
            index=models.Index(
                fields=["is_active", "-last_activity"],
                name="chat_opench_is_acti_b6f808_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="openchatparticipant",
            index=models.Index(
                fields=["room", "is_active", "-joined_at"],
                name="chat_opench_room_id_a15b5e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="openchatparticipant",
            index=models.Index(
                fields=["user", "is_active"], name="chat_opench_user_id_1fd044_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="openchatparticipant",
            unique_together={("user", "room")},
        ),
        migrations.AddIndex(
            model_name="openchatmessage",
            index=models.Index(
                fields=["room", "-created_at"], name="chat_opench_room_id_175d45_idx"
            ),
        ),
    ]
