# Generated by Django 5.1.11 on 2025-11-09 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_openchatparticipant_openchatroom_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenChatFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Favorited At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Open Chat Favorite",
                "verbose_name_plural": "Open Chat Favorites",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpenChatKick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Kick Reason")),
                (
                    "kicked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kicked At"),
                ),
                (
                    "ban_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for permanent ban",
                        null=True,
                        verbose_name="Ban Until",
                    ),
                ),
            ],
            options={
                "verbose_name": "Open Chat Kick",
                "verbose_name_plural": "Open Chat Kicks",
                "ordering": ["-kicked_at"],
            },
        ),
        migrations.AddField(
            model_name="openchatparticipant",
            name="admin_granted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Admin Granted At"
            ),
        ),
        migrations.AddField(
            model_name="openchatparticipant",
            name="is_admin",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Is Admin"
            ),
        ),
        migrations.AddField(
            model_name="openchatroom",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_open_chat_rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddIndex(
            model_name="openchatparticipant",
            index=models.Index(
                fields=["room", "is_admin"], name="chat_opench_room_id_d73bad_idx"
            ),
        ),
        migrations.AddField(
            model_name="openchatfavorite",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="chat.openchatroom",
                verbose_name="Room",
            ),
        ),
        migrations.AddField(
            model_name="openchatfavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_open_chats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="openchatkick",
            name="kicked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="open_chat_kicks_performed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kicked By",
            ),
        ),
        migrations.AddField(
            model_name="openchatkick",
            name="kicked_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="open_chat_kicks_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kicked User",
            ),
        ),
        migrations.AddField(
            model_name="openchatkick",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kick_records",
                to="chat.openchatroom",
                verbose_name="Room",
            ),
        ),
        migrations.AddIndex(
            model_name="openchatfavorite",
            index=models.Index(
                fields=["user", "-created_at"], name="chat_opench_user_id_aafdf2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="openchatfavorite",
            unique_together={("user", "room")},
        ),
        migrations.AddIndex(
            model_name="openchatkick",
            index=models.Index(
                fields=["room", "kicked_user"], name="chat_opench_room_id_156c3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="openchatkick",
            index=models.Index(
                fields=["room", "-kicked_at"], name="chat_opench_room_id_55a12c_idx"
            ),
        ),
    ]
