# Generated by Django 5.1.11 on 2025-11-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_openchatfavorite_openchatkick_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openchatroom",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="Is Public"),
        ),
        migrations.AddField(
            model_name="openchatroom",
            name="password",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Password"
            ),
        ),
    ]
