# Generated by Django 5.1.11 on 2025-11-16 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_openchatroom_is_public_openchatroom_password"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_type", "created_at"],
                name="chat_report_report__0b0fc6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["reporter", "status"], name="chat_report_reporte_32f3f5_idx"
            ),
        ),
    ]
