# Generated by Django 5.1.11 on 2025-11-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_report_chat_report_report__0b0fc6_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousmatchingpreference",
            name="chat_mode",
            field=models.CharField(
                choices=[("text", "글 채팅"), ("video", "영상 채팅")],
                default="text",
                help_text="채팅 모드 선택 (글/영상)",
                max_length=10,
            ),
        ),
    ]
