# Generated by Django 5.1.11 on 2025-11-16 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_anonymousmatchingpreference_chat_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("accepted", "수락됨"),
                            ("rejected", "거절됨"),
                        ],
                        default="pending",
                        help_text="요청 상태",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="익명 채팅방",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_requests",
                        to="chat.conversation",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="연결 요청을 받은 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="연결 요청을 보낸 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "status"],
                        name="chat_connec_convers_a752fd_idx",
                    ),
                    models.Index(
                        fields=["requester", "status"],
                        name="chat_connec_request_a06729_idx",
                    ),
                    models.Index(
                        fields=["receiver", "status"],
                        name="chat_connec_receive_0f1752_idx",
                    ),
                ],
                "unique_together": {("conversation", "requester", "receiver")},
            },
        ),
    ]
