# Generated by Django 5.1.11 on 2025-11-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_connectionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="만료 시간"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_expired",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="만료 여부"
            ),
        ),
    ]
