# Generated by Django 5.1.11 on 2025-11-30 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_message_expires_at_message_is_expired"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="evidence_viewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="증거 열람 시간"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="evidence_viewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evidence_views",
                to=settings.AUTH_USER_MODEL,
                verbose_name="증거 열람자",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="message_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="신고 당시 대화 내역 (최근 50개)",
                null=True,
                verbose_name="메시지 증거",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="video_frame",
            field=models.ImageField(
                blank=True,
                help_text="화상 채팅 신고 시 캡처된 화면",
                null=True,
                upload_to="report_evidence/video/",
                verbose_name="화상 채팅 캡처",
            ),
        ),
        migrations.CreateModel(
            name="ConversationBuffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "messages_json",
                    models.JSONField(
                        default=list,
                        help_text="최근 50개 메시지 저장",
                        verbose_name="메시지 버퍼",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="업데이트 시간"),
                ),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_buffer",
                        to="chat.conversation",
                        verbose_name="대화방",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation Buffer",
                "verbose_name_plural": "Conversation Buffers",
            },
        ),
    ]
