# Generated by Django 5.1.11 on 2026-02-24 13:08

from django.db import migrations


def migrate_marketlens_data(apps, schema_editor):
    """
    기존 posts_post 테이블에서 ticker가 있는 MarketLens 게시글을 community_posts로 복사.
    관련 댓글, 좋아요도 함께 복사.
    원본 데이터는 삭제하지 않음 (검증 후 별도 정리).
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # 1. ticker가 있는 게시글 복사 → community_posts
        # posts_post에는 like_count/comment_count가 없으므로 서브쿼리로 계산
        cursor.execute("""
            INSERT INTO community_posts (ticker, title, content, author_id, created_at, updated_at,
                                         like_count, comment_count, view_count, is_deleted, is_hidden)
            SELECT
                p.ticker,
                p.title,
                p.content,
                p.author_id,
                p.created_at,
                p.updated_at,
                COALESCE((SELECT COUNT(*) FROM posts_like l WHERE l.post_id = p.id), 0),
                COALESCE((SELECT COUNT(*) FROM posts_comment c WHERE c.post_id = p.id AND c.is_deleted_by_report = false), 0),
                0,
                p.is_deleted_by_report,
                false
            FROM posts_post p
            WHERE p.ticker IS NOT NULL AND p.ticker != ''
            ORDER BY p.id
        """)

        # 2. 매핑 테이블 생성 (old post_id → new community post_id)
        # 같은 순서로 삽입되었으므로 row_number 기반 매핑
        cursor.execute("""
            CREATE TEMPORARY TABLE _post_id_map AS
            SELECT
                old_posts.id AS old_id,
                new_posts.id AS new_id
            FROM (
                SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn
                FROM posts_post
                WHERE ticker IS NOT NULL AND ticker != ''
            ) old_posts
            JOIN (
                SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn
                FROM community_posts
            ) new_posts ON old_posts.rn = new_posts.rn
        """)

        # 3. 해당 게시글의 댓글 복사 → community_comments (parent=None, 대댓글 없음)
        cursor.execute("""
            INSERT INTO community_comments (post_id, author_id, content, parent_id,
                                            created_at, updated_at, like_count, is_deleted)
            SELECT
                pm.new_id,
                c.author_id,
                c.content,
                NULL,
                c.created_at,
                c.updated_at,
                COALESCE((SELECT COUNT(*) FROM posts_commentlike cl WHERE cl.comment_id = c.id), 0),
                c.is_deleted_by_report
            FROM posts_comment c
            JOIN _post_id_map pm ON pm.old_id = c.post_id
            ORDER BY c.id
        """)

        # 4. 댓글 매핑 테이블
        cursor.execute("""
            CREATE TEMPORARY TABLE _comment_id_map AS
            SELECT
                old_comments.id AS old_id,
                new_comments.id AS new_id
            FROM (
                SELECT c.id, ROW_NUMBER() OVER (ORDER BY c.id) AS rn
                FROM posts_comment c
                JOIN _post_id_map pm ON pm.old_id = c.post_id
            ) old_comments
            JOIN (
                SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn
                FROM community_comments
            ) new_comments ON old_comments.rn = new_comments.rn
        """)

        # 5. 게시글 좋아요 복사 → community_post_likes
        cursor.execute("""
            INSERT INTO community_post_likes (post_id, user_id, created_at)
            SELECT
                pm.new_id,
                l.user_id,
                l.created_at
            FROM posts_like l
            JOIN _post_id_map pm ON pm.old_id = l.post_id
        """)

        # 6. 댓글 좋아요 복사 → community_comment_likes
        cursor.execute("""
            INSERT INTO community_comment_likes (comment_id, user_id, created_at)
            SELECT
                cm.new_id,
                cl.user_id,
                cl.created_at
            FROM posts_commentlike cl
            JOIN _comment_id_map cm ON cm.old_id = cl.comment_id
        """)

        # 7. 임시 테이블 정리
        cursor.execute("DROP TABLE IF EXISTS _comment_id_map")
        cursor.execute("DROP TABLE IF EXISTS _post_id_map")


def reverse_migration(apps, schema_editor):
    """역방향 마이그레이션: community 테이블 데이터 삭제"""
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM community_comment_likes")
        cursor.execute("DELETE FROM community_post_likes")
        cursor.execute("DELETE FROM community_comments")
        cursor.execute("DELETE FROM community_posts")


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
        ("posts", "0012_commentlike"),  # posts 앱 최신 마이그레이션에 의존
    ]

    operations = [
        migrations.RunPython(migrate_marketlens_data, reverse_migration),
    ]
