# Generated by Django 5.1.11 on 2025-11-06 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_private",
            field=models.BooleanField(default=False, verbose_name="Private Profile"),
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Blocked User",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocking",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Blocker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block",
                "verbose_name_plural": "Blocks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["blocker", "-created_at"],
                        name="accounts_bl_blocker_ed90b7_idx",
                    ),
                    models.Index(
                        fields=["blocked", "-created_at"],
                        name="accounts_bl_blocked_a86280_idx",
                    ),
                ],
                "unique_together": {("blocker", "blocked")},
            },
        ),
    ]
