# Generated by Django 5.1.11 on 2025-11-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_is_private_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deactivation Date"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="deletion_requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deletion Request Date"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deactivated",
            field=models.BooleanField(
                default=False, verbose_name="Account Deactivated"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_followers_list",
            field=models.CharField(
                choices=[
                    ("everyone", "Everyone"),
                    ("followers", "Followers Only"),
                    ("nobody", "Nobody"),
                ],
                default="everyone",
                max_length=20,
                verbose_name="Followers List Visibility",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_following_list",
            field=models.CharField(
                choices=[
                    ("everyone", "Everyone"),
                    ("followers", "Followers Only"),
                    ("nobody", "Nobody"),
                ],
                default="everyone",
                max_length=20,
                verbose_name="Following List Visibility",
            ),
        ),
    ]
