# Generated by Django 5.1.11 on 2025-11-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_deactivated_at_user_deletion_requested_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "남성"),
                    ("female", "여성"),
                    ("other", "기타"),
                    ("prefer_not_to_say", "밝히지 않음"),
                ],
                max_length=20,
                null=True,
                verbose_name="성별",
            ),
        ),
    ]
