# Generated by Django 5.1.11 on 2025-11-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_supportticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="report_count",
            field=models.IntegerField(
                default=0,
                help_text="resolved/reviewing 상태 신고만 카운트",
                verbose_name="누적 신고 횟수",
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="status",
            field=models.CharField(
                choices=[("pending", "대기 중"), ("answered", "답변 완료")],
                default="pending",
                max_length=20,
                verbose_name="상태",
            ),
        ),
    ]
