# Generated by Django 5.1.11 on 2025-11-16 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_report_count_alter_supportticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ban_reason",
            field=models.TextField(blank=True, verbose_name="Ban Reason"),
        ),
        migrations.AddField(
            model_name="user",
            name="banned_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ban Date"),
        ),
        migrations.AddField(
            model_name="user",
            name="banned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="banned_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Banned By Admin",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False, verbose_name="Account Banned"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_suspended",
            field=models.BooleanField(default=False, verbose_name="Account Suspended"),
        ),
        migrations.AddField(
            model_name="user",
            name="suspended_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Suspension Start Date"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="suspended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suspended_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Suspended By Admin",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="suspended_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Suspension End Date"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="suspension_reason",
            field=models.TextField(blank=True, verbose_name="Suspension Reason"),
        ),
    ]
