# Generated by Django 5.1.11 on 2025-11-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_ban_reason_user_banned_at_user_banned_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="native_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ko", "한국어"),
                    ("en", "English"),
                    ("ja", "日本語"),
                    ("zh", "中文"),
                    ("es", "Español"),
                    ("fr", "Français"),
                    ("de", "Deutsch"),
                ],
                default="",
                max_length=2,
                verbose_name="모국어",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="target_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ko", "한국어"),
                    ("en", "English"),
                    ("ja", "日本語"),
                    ("zh", "中文"),
                    ("es", "Español"),
                    ("fr", "Français"),
                    ("de", "Deutsch"),
                ],
                default="",
                max_length=2,
                verbose_name="학습 언어",
            ),
        ),
    ]
