# Generated by Django 5.1.11 on 2025-11-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_native_language_user_target_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                (
                    "attempted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시도 시간"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 주소"
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset Attempt",
                "verbose_name_plural": "Password Reset Attempts",
                "ordering": ["-attempted_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "-attempted_at"],
                        name="accounts_pa_email_d96cf5_idx",
                    )
                ],
            },
        ),
    ]
