# Generated by Django 5.1.11 on 2025-11-30 04:13

from django.db import migrations, models


def migrate_staff_to_prime(apps, schema_editor):
    """기존 Staff 사용자를 Prime으로 전환하고 Gold 기능 활성화"""
    User = apps.get_model('accounts', 'User')

    # is_staff=True인 모든 사용자를 Prime으로 전환
    staff_users = User.objects.filter(is_staff=True)
    count = staff_users.count()

    if count > 0:
        staff_users.update(is_prime=True, is_gold=True)
        print(f"✅ {count}명의 Staff 사용자를 Prime으로 전환했습니다.")
    else:
        print("ℹ️  전환할 Staff 사용자가 없습니다.")


def reverse_migration(apps, schema_editor):
    """롤백 시 Prime을 Staff로 복원"""
    User = apps.get_model('accounts', 'User')

    # is_prime=True인 사용자의 is_gold를 False로 복원
    # (is_staff는 이미 True이므로 유지)
    User.objects.filter(is_prime=True).update(is_gold=False)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_passwordresetattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_gold",
            field=models.BooleanField(default=False, verbose_name="골드 사용자"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_prime",
            field=models.BooleanField(default=False, verbose_name="프리미엄 관리자"),
        ),
        # 데이터 마이그레이션: 기존 Staff → Prime 전환
        migrations.RunPython(migrate_staff_to_prime, reverse_migration),
    ]
