# Generated by Django 5.1.11 on 2025-11-30 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_user_is_gold_user_is_prime"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("abuse", "욕설/비방"),
                            ("spam", "스팸/광고"),
                            ("inappropriate", "부적절한 내용"),
                            ("harassment", "성희롱"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                        verbose_name="신고 유형",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="상세 설명")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("reviewing", "검토 중"),
                            ("resolved", "처리 완료"),
                            ("dismissed", "기각"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="신고 시간"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="검토 시간"
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="관리자 메모"),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reports_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신고된 사용자",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reports_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신고자",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_reports_resolved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="처리 관리자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 신고",
                "verbose_name_plural": "사용자 신고",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reporter", "-created_at"],
                        name="accounts_us_reporte_360f26_idx",
                    ),
                    models.Index(
                        fields=["reported_user", "-created_at"],
                        name="accounts_us_reporte_803103_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="accounts_us_status_b1d3cb_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("reporter", "reported_user", "report_type"),
                        name="unique_pending_user_report",
                    )
                ],
            },
        ),
    ]
