# Generated by Django 5.1.11 on 2025-12-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_userreport"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="block",
            name="accounts_bl_blocker_ed90b7_idx",
        ),
        migrations.RemoveIndex(
            model_name="block",
            name="accounts_bl_blocked_a86280_idx",
        ),
        migrations.AddField(
            model_name="block",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="block",
            name="unblocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                fields=["blocker", "is_active", "-created_at"],
                name="accounts_bl_blocker_89a35d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                fields=["blocked", "is_active", "-created_at"],
                name="accounts_bl_blocked_8bcef1_idx",
            ),
        ),
    ]
