# Generated by Django 5.1.11 on 2025-12-08 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_block_accounts_bl_blocker_ed90b7_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("terms", "이용약관"),
                            ("privacy", "개인정보처리방침"),
                            ("cookies", "쿠키 정책"),
                            ("community", "커뮤니티 가이드라인"),
                        ],
                        max_length=20,
                        verbose_name="문서 유형",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ko", "한국어"),
                            ("en", "English"),
                            ("ja", "日本語"),
                            ("es", "Español"),
                        ],
                        max_length=2,
                        verbose_name="언어",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                (
                    "content",
                    models.TextField(
                        help_text="HTML 형식으로 작성", verbose_name="내용"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="예: 1.0, 1.1, 2.0",
                        max_length=20,
                        verbose_name="버전",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="언어별로 하나의 문서만 활성화 가능",
                        verbose_name="활성 상태",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="이 버전이 유효하게 되는 날짜", verbose_name="시행일"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시간"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_docs_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_docs_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "법적 문서",
                "verbose_name_plural": "법적 문서",
                "ordering": ["-effective_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LegalDocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                ("version", models.CharField(max_length=20, verbose_name="버전")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="accounts.legaldocument",
                        verbose_name="문서",
                    ),
                ),
            ],
            options={
                "verbose_name": "법적 문서 버전",
                "verbose_name_plural": "법적 문서 버전",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="legaldocument",
            index=models.Index(
                fields=["document_type", "language", "is_active"],
                name="accounts_le_documen_8cc60b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="legaldocument",
            index=models.Index(
                fields=["document_type", "-effective_date"],
                name="accounts_le_documen_b020dd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="legaldocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("document_type", "language"),
                name="unique_active_legal_document",
            ),
        ),
        migrations.AddIndex(
            model_name="legaldocumentversion",
            index=models.Index(
                fields=["document", "-created_at"],
                name="accounts_le_documen_be0c02_idx",
            ),
        ),
    ]
