# Generated by Django 5.1.11 on 2026-02-11 11:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_legaldocument_legaldocumentversion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("master", "Master"),
                    ("manager", "Manager"),
                    ("gold", "Gold User"),
                    ("regular", "Regular"),
                ],
                default="regular",
                help_text="MarketLens 권한 시스템: master > manager > gold > regular",
                max_length=10,
                verbose_name="사용자 역할",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="프로필 사진 (자동으로 1024x1024, 85% 품질로 최적화됩니다)",
                null=True,
                upload_to=accounts.models.profile_picture_upload_path,
                verbose_name="프로필 사진",
            ),
        ),
    ]
