# Generated by Django 5.1.11 on 2026-02-26 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_user_role_alter_user_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationRateLimit",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_general_notified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "accounts_notificationratelimit",
            },
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")], max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_devicetoken",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="accounts_de_user_id_d068f5_idx",
                    ),
                    models.Index(fields=["token"], name="accounts_de_token_6c786c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_notificationsubscription",
                "indexes": [
                    models.Index(
                        fields=["ticker", "is_active"],
                        name="accounts_no_ticker_97ea50_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="accounts_no_user_id_b91a86_idx",
                    ),
                ],
                "unique_together": {("user", "ticker")},
            },
        ),
    ]
