# Generated by Django 5.1.11 on 2026-02-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_add_fcm_devicetoken_subscription_ratelimit"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetoken",
            name="language",
            field=models.CharField(default="en", max_length=5),
        ),
    ]
