# Generated by Django 5.1.11 on 2026-02-28 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_devicetoken_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("notification_type", models.CharField(max_length=30)),
                ("ticker", models.CharField(blank=True, default="", max_length=50)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_notification_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_no_user_id_1522c1_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="accounts_no_user_id_e7a5be_idx",
                    ),
                ],
            },
        ),
    ]
