# Generated by Django 5.1.11 on 2025-10-12 10:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("default", "국가별 기본방"),
                            ("user_created", "사용자 생성방"),
                        ],
                        default="user_created",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="채팅방 제목", max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="채팅방 설명", max_length=500
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="국가 코드 (ISO 3166-1 alpha-3)", max_length=3
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="카테고리 (예: 스포츠, 음악, 게임 등)",
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="태그 (쉼표로 구분)", max_length=200
                    ),
                ),
                (
                    "participant_count",
                    models.IntegerField(default=0, help_text="현재 참여자 수"),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        default=100, help_text="최대 참여자 수 (0이면 무제한)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        help_text="채팅방 생성자 (기본방은 null)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_open_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "오픈 채팅방",
                "verbose_name_plural": "오픈 채팅방 목록",
                "ordering": ["-participant_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpenChatParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_read_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="현재 접속 중인지"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_chat_participants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="chat.openchatroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "오픈 채팅방 참여자",
                "verbose_name_plural": "오픈 채팅방 참여자 목록",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="OpenChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "텍스트"),
                            ("system", "시스템 알림"),
                            ("join", "입장 알림"),
                            ("leave", "퇴장 알림"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="open_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.openchatroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "오픈 채팅 메시지",
                "verbose_name_plural": "오픈 채팅 메시지 목록",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="openchatroom",
            index=models.Index(
                fields=["country_code", "room_type"],
                name="chat_opench_country_29bc66_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="openchatroom",
            index=models.Index(
                fields=["category"], name="chat_opench_categor_9e3373_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="openchatroom",
            index=models.Index(
                fields=["-participant_count"], name="chat_opench_partici_b47783_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="openchatparticipant",
            unique_together={("room", "user")},
        ),
        migrations.AddIndex(
            model_name="openchatmessage",
            index=models.Index(
                fields=["room", "-created_at"], name="chat_opench_room_id_175d45_idx"
            ),
        ),
    ]
