# Generated by Django 5.1.11 on 2025-10-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_openchatroom_openchatparticipant_openchatmessage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openchatroom",
            name="country_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="국가 코드 (ISO 3166-1 alpha-3)",
                max_length=3,
            ),
        ),
    ]
