# Generated by Django 5.1.11 on 2025-10-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_openchatroom_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="openchatroom",
            name="is_public",
            field=models.BooleanField(default=True, help_text="공개 채팅방 여부"),
        ),
        migrations.AddField(
            model_name="openchatroom",
            name="password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="비공개 채팅방 비밀번호",
                max_length=50,
            ),
        ),
    ]
