# Generated by Django 5.1.11 on 2025-10-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_openchatroom_is_public_openchatroom_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("text", "일반 텍스트"), ("system", "시스템 메시지")],
                default="text",
                max_length=20,
            ),
        ),
    ]
