# Generated by Django 5.1.11 on 2025-10-25 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_message_message_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matched_at",
                    models.DateTimeField(auto_now_add=True, help_text="매칭된 시각"),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, help_text="차단 여부"),
                ),
                (
                    "last_message_preview",
                    models.TextField(
                        blank=True, help_text="마지막 메시지 미리보기", max_length=100
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        blank=True,
                        help_text="채팅방 (삭제되면 null)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="histories",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "matched_user",
                    models.ForeignKey(
                        help_text="매칭된 상대방",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matched_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="이력을 소유한 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "매칭 이력",
                "verbose_name_plural": "매칭 이력 목록",
                "db_table": "match_history",
                "ordering": ["-matched_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-matched_at"],
                        name="match_histo_user_id_065d5d_idx",
                    ),
                    models.Index(
                        fields=["matched_user", "-matched_at"],
                        name="match_histo_matched_31cb0a_idx",
                    ),
                ],
            },
        ),
    ]
