# Generated by Django 5.1.11 on 2025-10-25 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_matchhistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="blocked_for_user",
            field=models.ForeignKey(
                blank=True,
                help_text="이 메시지를 볼 수 없는 사용자 (차단 당시 메시지)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hidden_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
