# Generated by Django 5.1.11 on 2025-11-09 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Course Title"),
                ),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("description", models.TextField(verbose_name="Course Description")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "입문"),
                            ("elementary", "초급"),
                            ("intermediate", "중급"),
                            ("advanced", "고급"),
                        ],
                        db_index=True,
                        default="beginner",
                        max_length=20,
                        verbose_name="Course Level",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("conversation", "회화"),
                            ("business", "비즈니스"),
                            ("travel", "여행"),
                            ("daily", "일상"),
                            ("exercise", "운동"),
                            ("culture", "문화"),
                            ("grammar", "문법"),
                            ("vocabulary", "어휘"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "is_system_content",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="System-provided courses are protected from direct editing",
                        verbose_name="System Content",
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked courses can only be edited by moderators",
                        verbose_name="Locked",
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("contributor_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_activity", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["-last_activity", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Lesson Title"),
                ),
                ("slug", models.SlugField(max_length=250)),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Order in Course"),
                ),
                (
                    "current_content",
                    models.TextField(blank=True, verbose_name="Current Content"),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked lessons require moderator approval for edits",
                        verbose_name="Locked",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True,
                        help_text="All edits must be approved before going live",
                        verbose_name="Requires Approval",
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("edit_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="learning.course",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
                "ordering": ["course", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="LessonBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarked_by",
                        to="learning.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Bookmark",
                "verbose_name_plural": "Lesson Bookmarks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonContributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_edits", models.IntegerField(default=0)),
                ("approved_edits", models.IntegerField(default=0)),
                ("rejected_edits", models.IntegerField(default=0)),
                ("reputation_score", models.IntegerField(default=0)),
                (
                    "is_trusted",
                    models.BooleanField(
                        default=False,
                        help_text="Trusted contributors can bypass approval workflow",
                        verbose_name="Trusted Contributor",
                    ),
                ),
                ("first_contribution", models.DateTimeField(auto_now_add=True)),
                ("last_contribution", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="learning.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_contributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Contributor",
                "verbose_name_plural": "Lesson Contributors",
            },
        ),
        migrations.CreateModel(
            name="LessonVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField(verbose_name="Version Number")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "edit_summary",
                    models.CharField(
                        blank=True,
                        help_text="Brief description of changes made",
                        max_length=500,
                        verbose_name="Edit Summary",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("auto_approved", "Auto-Approved"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="Review Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lesson_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="learning.lesson",
                        verbose_name="Lesson",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Version",
                "verbose_name_plural": "Lesson Versions",
                "ordering": ["lesson", "-version_number"],
            },
        ),
        migrations.CreateModel(
            name="LessonComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Comment")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="learning.lesson",
                        verbose_name="Lesson",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="learning.lessoncomment",
                        verbose_name="Parent Comment",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="learning.lessonversion",
                        verbose_name="Version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Comment",
                "verbose_name_plural": "Lesson Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_lesson",
                to="learning.lessonversion",
                verbose_name="Current Version",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["level", "category", "-last_activity"],
                name="learning_co_level_46c9e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["is_published", "-last_activity"],
                name="learning_co_is_publ_8832a9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessonbookmark",
            unique_together={("user", "lesson")},
        ),
        migrations.AddIndex(
            model_name="lessoncontributor",
            index=models.Index(
                fields=["user", "-reputation_score"],
                name="learning_le_user_id_93ca02_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lessoncontributor",
            index=models.Index(
                fields=["lesson", "-reputation_score"],
                name="learning_le_lesson__adda2c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessoncontributor",
            unique_together={("user", "lesson")},
        ),
        migrations.AddIndex(
            model_name="lessonversion",
            index=models.Index(
                fields=["lesson", "-version_number"],
                name="learning_le_lesson__432431_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonversion",
            index=models.Index(
                fields=["author", "-created_at"], name="learning_le_author__888643_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonversion",
            index=models.Index(
                fields=["status", "-created_at"], name="learning_le_status_2efe9c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessonversion",
            unique_together={("lesson", "version_number")},
        ),
        migrations.AddIndex(
            model_name="lessoncomment",
            index=models.Index(
                fields=["lesson", "-created_at"], name="learning_le_lesson__7b0455_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["course", "order"], name="learning_le_course__30756f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("course", "slug")},
        ),
    ]
