# Generated by Django 5.1.11 on 2025-11-13 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SituationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text='Unique identifier (e.g., "daily", "travel", "business")',
                        max_length=50,
                        unique=True,
                        verbose_name="Category Code",
                    ),
                ),
                (
                    "name_ko",
                    models.CharField(max_length=100, verbose_name="Korean Name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="English Name"),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text='Emoji icon (e.g., "🏠", "✈️", "💼")',
                        max_length=10,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Situation Category",
                "verbose_name_plural": "Situation Categories",
                "ordering": ["order", "name_ko"],
            },
        ),
        migrations.CreateModel(
            name="SituationLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ko",
                    models.CharField(max_length=200, verbose_name="Korean Title"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="English Title"),
                ),
                ("slug", models.SlugField(max_length=250, unique=True)),
                (
                    "language",
                    models.CharField(
                        db_index=True,
                        help_text='Language code (e.g., "EN", "KO", "ES")',
                        max_length=5,
                        verbose_name="Target Language",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Order in Category"),
                ),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="learning.situationcategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Situation Lesson",
                "verbose_name_plural": "Situation Lessons",
                "ordering": ["category", "order", "title_ko"],
            },
        ),
        migrations.CreateModel(
            name="SituationExpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expression",
                    models.CharField(
                        help_text="Korean expression",
                        max_length=200,
                        verbose_name="Expression",
                    ),
                ),
                (
                    "translation",
                    models.CharField(
                        help_text="English translation",
                        max_length=200,
                        verbose_name="Translation",
                    ),
                ),
                (
                    "pronunciation",
                    models.CharField(
                        help_text="Pronunciation guide in Korean",
                        max_length=200,
                        verbose_name="Pronunciation",
                    ),
                ),
                (
                    "situation_context",
                    models.TextField(
                        help_text="When and how to use this expression",
                        verbose_name="Situation Context",
                    ),
                ),
                (
                    "vocabulary",
                    models.JSONField(
                        default=list,
                        help_text='Array of vocabulary items: [{"word": "...", "meaning": "...", "example": "..."}]',
                        verbose_name="Vocabulary",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Order in Lesson"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expressions",
                        to="learning.situationlesson",
                        verbose_name="Lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Situation Expression",
                "verbose_name_plural": "Situation Expressions",
                "ordering": ["lesson", "order"],
            },
        ),
        migrations.AddIndex(
            model_name="situationlesson",
            index=models.Index(
                fields=["category", "language", "order"],
                name="learning_si_categor_945cfb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="situationlesson",
            index=models.Index(
                fields=["is_published", "-view_count"],
                name="learning_si_is_publ_191658_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="situationlesson",
            unique_together={("category", "slug")},
        ),
        migrations.AddIndex(
            model_name="situationexpression",
            index=models.Index(
                fields=["lesson", "order"], name="learning_si_lesson__376acc_idx"
            ),
        ),
    ]
