# Generated by Django 5.1.11 on 2025-11-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_remove_course_lesson_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="course",
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="current_version",
        ),
        migrations.RemoveField(
            model_name="lessonbookmark",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="lessoncomment",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="lessonversion",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="lessoncontributor",
            name="lesson",
        ),
        migrations.AlterUniqueTogether(
            name="lessonbookmark",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="lessonbookmark",
            name="user",
        ),
        migrations.RemoveField(
            model_name="lessoncomment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="lessoncomment",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="lessoncomment",
            name="version",
        ),
        migrations.AlterUniqueTogether(
            name="lessoncontributor",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="lessoncontributor",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="lessonversion",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="lessonversion",
            name="author",
        ),
        migrations.RemoveField(
            model_name="lessonversion",
            name="reviewed_by",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Lesson",
        ),
        migrations.DeleteModel(
            name="LessonBookmark",
        ),
        migrations.DeleteModel(
            name="LessonComment",
        ),
        migrations.DeleteModel(
            name="LessonContributor",
        ),
        migrations.DeleteModel(
            name="LessonVersion",
        ),
    ]
