# Generated by Django 5.1.11 on 2025-10-15 11:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("user", "사용자"),
                            ("post", "게시글"),
                            ("comment", "댓글"),
                            ("message", "메시지"),
                            ("open_chat_message", "오픈 채팅 메시지"),
                        ],
                        help_text="신고 타입",
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "스팸/광고"),
                            ("harassment", "욕설/비방"),
                            ("inappropriate", "부적절한 콘텐츠"),
                            ("violence", "폭력적 콘텐츠"),
                            ("sexual", "성적 콘텐츠"),
                            ("illegal", "불법 정보"),
                            ("fraud", "사기/사칭"),
                            ("other", "기타"),
                        ],
                        help_text="신고 사유",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="상세 설명", max_length=500),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("reviewing", "검토 중"),
                            ("resolved", "처리 완료"),
                            ("rejected", "반려됨"),
                        ],
                        default="pending",
                        help_text="처리 상태",
                        max_length=20,
                    ),
                ),
                (
                    "resolution",
                    models.TextField(blank=True, help_text="처리 결과", max_length=500),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="처리 완료 시간", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        help_text="신고한 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="검토 담당자",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "신고",
                "verbose_name_plural": "신고 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSanction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sanction_type",
                    models.CharField(
                        choices=[
                            ("warning", "경고"),
                            ("temp_ban", "일시 정지"),
                            ("perm_ban", "영구 차단"),
                        ],
                        help_text="제재 유형",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="제재 사유", max_length=500)),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="제재 시작 시간"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="제재 종료 시간 (영구 차단은 null)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="활성화 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_report",
                    models.ForeignKey(
                        blank=True,
                        help_text="관련 신고",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sanctions",
                        to="moderation.report",
                    ),
                ),
                (
                    "sanctioned_by",
                    models.ForeignKey(
                        help_text="제재를 부여한 관리자",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sanctions_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="제재 대상 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sanctions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 제재",
                "verbose_name_plural": "사용자 제재 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("review_report", "신고 검토"),
                            ("resolve_report", "신고 처리"),
                            ("reject_report", "신고 반려"),
                            ("issue_warning", "경고 부여"),
                            ("issue_ban", "차단 부여"),
                            ("remove_ban", "차단 해제"),
                            ("delete_content", "콘텐츠 삭제"),
                            ("restore_content", "콘텐츠 복구"),
                        ],
                        help_text="액션 타입",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="액션 설명", max_length=500),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        help_text="관리자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "관리 로그",
                "verbose_name_plural": "관리 로그 목록",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["moderator", "-created_at"],
                        name="moderation__moderat_68c327_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="moderation__action__f374ad_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["status", "-created_at"], name="moderation__status_282342_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_type", "-created_at"],
                name="moderation__report__edc06e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usersanction",
            index=models.Index(
                fields=["user", "-created_at"], name="moderation__user_id_1d9eea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersanction",
            index=models.Index(
                fields=["sanction_type", "-created_at"],
                name="moderation__sanctio_085f53_idx",
            ),
        ),
    ]
