# Generated by Django 5.1.11 on 2025-11-27 12:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="번호",
                    ),
                ),
                (
                    "first_prize_count",
                    models.IntegerField(default=0, verbose_name="1등 출현 횟수"),
                ),
                (
                    "second_prize_count",
                    models.IntegerField(default=0, verbose_name="2등 출현 횟수"),
                ),
                (
                    "bonus_count",
                    models.IntegerField(default=0, verbose_name="보너스 출현 횟수"),
                ),
                (
                    "total_count",
                    models.IntegerField(default=0, verbose_name="전체 출현 횟수"),
                ),
                (
                    "last_appeared_round",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="마지막 출현 회차"
                    ),
                ),
                (
                    "last_appeared_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="마지막 출현일"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "번호 통계",
                "verbose_name_plural": "번호 통계 목록",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="LottoDraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round_number",
                    models.IntegerField(unique=True, verbose_name="회차 번호"),
                ),
                ("draw_date", models.DateField(verbose_name="추첨일")),
                (
                    "number1",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="번호 1",
                    ),
                ),
                (
                    "number2",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="번호 2",
                    ),
                ),
                (
                    "number3",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="번호 3",
                    ),
                ),
                (
                    "number4",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="번호 4",
                    ),
                ),
                (
                    "number5",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="번호 5",
                    ),
                ),
                (
                    "number6",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="번호 6",
                    ),
                ),
                (
                    "bonus_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="보너스 번호",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "로또 추첨",
                "verbose_name_plural": "로또 추첨 목록",
                "ordering": ["-round_number"],
                "indexes": [
                    models.Index(
                        fields=["round_number"], name="lotto_lotto_round_n_cda4d1_idx"
                    ),
                    models.Index(
                        fields=["draw_date"], name="lotto_lotto_draw_da_080a5c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NumberCombination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "combination_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="조합 해시"
                    ),
                ),
                ("numbers", models.JSONField(verbose_name="번호 조합")),
                ("round_number", models.IntegerField(verbose_name="회차 번호")),
                ("rank", models.CharField(max_length=10, verbose_name="등수")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "번호 조합",
                "verbose_name_plural": "번호 조합 목록",
                "ordering": ["-round_number"],
                "indexes": [
                    models.Index(
                        fields=["combination_hash"],
                        name="lotto_numbe_combina_9c6b32_idx",
                    ),
                    models.Index(
                        fields=["round_number"], name="lotto_numbe_round_n_d73315_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserLottoNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField(verbose_name="회차 번호")),
                (
                    "number1",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="번호 1",
                    ),
                ),
                (
                    "number2",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="번호 2",
                    ),
                ),
                (
                    "number3",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="번호 3",
                    ),
                ),
                (
                    "number4",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="번호 4",
                    ),
                ),
                (
                    "number5",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="번호 5",
                    ),
                ),
                (
                    "number6",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="번호 6",
                    ),
                ),
                (
                    "matched_rank",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="당첨 등수"
                    ),
                ),
                (
                    "matched_count",
                    models.IntegerField(default=0, verbose_name="일치 개수"),
                ),
                (
                    "has_bonus",
                    models.BooleanField(default=False, verbose_name="보너스 일치"),
                ),
                (
                    "is_checked",
                    models.BooleanField(default=False, verbose_name="확인 완료"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotto_numbers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 로또 번호",
                "verbose_name_plural": "사용자 로또 번호 목록",
                "ordering": ["-round_number", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "round_number"],
                        name="lotto_userl_user_id_8f6c15_idx",
                    ),
                    models.Index(
                        fields=["round_number", "is_checked"],
                        name="lotto_userl_round_n_e04c7f_idx",
                    ),
                ],
            },
        ),
    ]
