# Generated by Django 5.1.11 on 2025-11-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lottodraw",
            name="first_prize_amount",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="1등 총당첨금"
            ),
        ),
        migrations.AddField(
            model_name="lottodraw",
            name="first_prize_winners",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="1등 당첨자수"
            ),
        ),
        migrations.AddField(
            model_name="lottodraw",
            name="second_prize_amount",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="2등 총당첨금"
            ),
        ),
        migrations.AddField(
            model_name="lottodraw",
            name="second_prize_winners",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="2등 당첨자수"
            ),
        ),
    ]
