# Generated by Django 5.1.11 on 2025-11-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotto", "0002_lottodraw_first_prize_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="numbercombination",
            name="combination_hash",
            field=models.CharField(max_length=64, verbose_name="조합 해시"),
        ),
        migrations.AlterUniqueTogether(
            name="numbercombination",
            unique_together={("combination_hash", "rank")},
        ),
        migrations.AddIndex(
            model_name="numbercombination",
            index=models.Index(fields=["rank"], name="lotto_numbe_rank_04087d_idx"),
        ),
    ]
