# Generated by Django 5.1.11 on 2025-11-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lotto", "0003_alter_numbercombination_combination_hash_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="numbercombination",
            unique_together=set(),
        ),
    ]
