# Generated by Django 5.1.11 on 2025-11-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotto", "0004_alter_numbercombination_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="OverlapStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank_pair",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="등수 쌍"
                    ),
                ),
                (
                    "overlap_count",
                    models.IntegerField(default=0, verbose_name="중복 개수"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 업데이트"),
                ),
            ],
            options={
                "verbose_name": "중복 통계",
                "verbose_name_plural": "중복 통계 목록",
                "ordering": ["rank_pair"],
            },
        ),
        migrations.CreateModel(
            name="OverlapDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank_pair",
                    models.CharField(
                        db_index=True, max_length=10, verbose_name="등수 쌍"
                    ),
                ),
                (
                    "combination_hash",
                    models.CharField(max_length=64, verbose_name="조합 해시"),
                ),
                ("numbers", models.JSONField(verbose_name="번호 조합")),
                (
                    "first_rank",
                    models.CharField(max_length=10, verbose_name="첫 번째 등수"),
                ),
                (
                    "first_rank_round",
                    models.IntegerField(verbose_name="첫 번째 등수 회차"),
                ),
                ("first_rank_date", models.DateField(verbose_name="첫 번째 등수 날짜")),
                (
                    "second_rank",
                    models.CharField(max_length=10, verbose_name="두 번째 등수"),
                ),
                (
                    "second_rank_round",
                    models.IntegerField(verbose_name="두 번째 등수 회차"),
                ),
                (
                    "second_rank_date",
                    models.DateField(verbose_name="두 번째 등수 날짜"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "중복 상세 정보",
                "verbose_name_plural": "중복 상세 정보 목록",
                "ordering": ["rank_pair", "-first_rank_round"],
                "indexes": [
                    models.Index(
                        fields=["rank_pair"], name="lotto_overl_rank_pa_ed40a9_idx"
                    ),
                    models.Index(
                        fields=["combination_hash"],
                        name="lotto_overl_combina_46cdd5_idx",
                    ),
                ],
            },
        ),
    ]
