# Generated by Django 5.1.11 on 2025-11-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotto", "0005_overlapstatistics_overlapdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlottonumber",
            name="strategy_type",
            field=models.CharField(
                choices=[
                    ("basic", "기본 스마트"),
                    ("strategy1", "추가전략1"),
                    ("strategy2", "추가전략2"),
                    ("strategy3", "추가전략3"),
                    ("strategy4", "추가전략4"),
                ],
                default="basic",
                max_length=20,
                verbose_name="생성 전략",
            ),
        ),
    ]
