# Generated by Django 5.1.11 on 2025-11-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotto", "0006_userlottonumber_strategy_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy_type",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="전략 타입"
                    ),
                ),
                ("round_number", models.IntegerField(verbose_name="계산 기준 회차")),
                (
                    "total_theoretical",
                    models.IntegerField(verbose_name="이론적 전체 조합 수"),
                ),
                ("excluded_count", models.IntegerField(verbose_name="제외된 조합 수")),
                ("remaining_count", models.IntegerField(verbose_name="남은 조합 수")),
                ("probability", models.FloatField(verbose_name="당첨 확률")),
                (
                    "improvement_ratio",
                    models.FloatField(verbose_name="일반 로또 대비 배수"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 업데이트"),
                ),
            ],
            options={
                "verbose_name": "전략 통계",
                "verbose_name_plural": "전략 통계 목록",
                "ordering": ["strategy_type"],
            },
        ),
    ]
