# Generated by Django 5.1.11 on 2025-11-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotto", "0007_strategystatistics"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyStatisticsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy_type",
                    models.CharField(max_length=20, verbose_name="전략 타입"),
                ),
                ("round_number", models.IntegerField(verbose_name="회차")),
                (
                    "total_theoretical",
                    models.IntegerField(verbose_name="이론적 전체 조합 수"),
                ),
                ("excluded_count", models.IntegerField(verbose_name="제외된 조합 수")),
                ("remaining_count", models.IntegerField(verbose_name="남은 조합 수")),
                ("probability", models.FloatField(verbose_name="당첨 확률")),
                (
                    "improvement_ratio",
                    models.FloatField(verbose_name="일반 로또 대비 배수"),
                ),
                (
                    "change_remaining",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="조합 수 변화"
                    ),
                ),
                (
                    "change_probability_pct",
                    models.FloatField(
                        blank=True, null=True, verbose_name="확률 변화 %"
                    ),
                ),
                (
                    "change_ratio",
                    models.FloatField(
                        blank=True, null=True, verbose_name="개선 배수 변화"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
            ],
            options={
                "verbose_name": "전략 통계 히스토리",
                "verbose_name_plural": "전략 통계 히스토리 목록",
                "ordering": ["-round_number", "strategy_type"],
                "indexes": [
                    models.Index(
                        fields=["strategy_type", "-round_number"],
                        name="lotto_strat_strateg_e9ce4e_idx",
                    )
                ],
                "unique_together": {("strategy_type", "round_number")},
            },
        ),
    ]
