# Generated by Django 5.1.11 on 2025-12-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotto", "0008_strategystatisticshistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlottonumber",
            name="matched_round",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="실제 당첨 회차"
            ),
        ),
    ]
