# Generated by Django 5.1.11 on 2025-11-06 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_follow"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="notification_settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "enable_message_notifications",
                    models.BooleanField(default=True, verbose_name="메시지 알림"),
                ),
                (
                    "enable_follow_notifications",
                    models.BooleanField(default=True, verbose_name="팔로우 알림"),
                ),
                (
                    "enable_post_notifications",
                    models.BooleanField(default=True, verbose_name="게시글 알림"),
                ),
                (
                    "enable_comment_notifications",
                    models.BooleanField(default=True, verbose_name="댓글 알림"),
                ),
                (
                    "enable_like_notifications",
                    models.BooleanField(default=True, verbose_name="좋아요 알림"),
                ),
                (
                    "enable_all_notifications",
                    models.BooleanField(default=True, verbose_name="모든 알림"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Settings",
                "verbose_name_plural": "Notification Settings",
            },
        ),
    ]
