# Generated by Django 5.1.11 on 2025-11-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("MESSAGE", "새 메시지"),
                    ("FOLLOW", "새 팔로워"),
                    ("POST", "팔로우한 유저의 새 게시글"),
                    ("COMMENT", "게시글에 댓글"),
                    ("LIKE", "게시글에 좋아요"),
                    ("REPORT", "신고 접수"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="알림 타입",
            ),
        ),
    ]
