# Generated by Django 5.1.11 on 2025-10-12 09:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("music", "음악"),
                            ("entertainment", "엔터테인먼트"),
                            ("travel", "여행"),
                            ("tech", "기술"),
                            ("language", "언어"),
                            ("relationship", "관계"),
                            ("sports", "스포츠"),
                            ("food", "음식"),
                            ("art", "예술"),
                            ("game", "게임"),
                            ("fitness", "운동/피트니스"),
                            ("book", "독서"),
                            ("movie", "영화"),
                            ("fashion", "패션"),
                            ("photography", "사진"),
                            ("other", "기타"),
                        ],
                        help_text="관심사 대분류",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="관심사 이름 (기본)", max_length=50, unique=True
                    ),
                ),
                ("name_ko", models.CharField(help_text="한국어 이름", max_length=50)),
                ("name_en", models.CharField(help_text="영어 이름", max_length=50)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="아이콘 이모지", max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "관심사",
                "verbose_name_plural": "관심사 목록",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("visitor", "Visitor"),
                            ("user", "User"),
                            ("premiumuser", "Premium User"),
                            ("manager", "Manager"),
                            ("prime", "Prime Admin"),
                            ("owner", "Owner"),
                        ],
                        default="visitor",
                        help_text="사용자 권한 레벨",
                        max_length=20,
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        help_text="사용자 닉네임 (최대 20자)",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-3 국가 코드", max_length=3
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, help_text="자기소개", max_length=500),
                ),
                (
                    "premium_until",
                    models.DateTimeField(
                        blank=True, help_text="프리미엄 만료 일시", null=True
                    ),
                ),
                (
                    "daily_match_count",
                    models.IntegerField(default=0, help_text="오늘 매칭 횟수"),
                ),
                (
                    "last_match_reset",
                    models.DateField(
                        auto_now_add=True, help_text="마지막 매칭 카운트 리셋 날짜"
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(default=False, help_text="계정 정지 여부"),
                ),
                (
                    "banned_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="정지 해제 일시 (None이면 영구)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_interests",
                        to="accounts.interest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 관심사",
                "verbose_name_plural": "사용자 관심사 목록",
                "unique_together": {("user", "interest")},
            },
        ),
    ]
