# Generated by Django 5.1.11 on 2025-10-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="이메일 (로그인 ID)", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(help_text="사용자명 (중복 가능)", max_length=150),
        ),
    ]
