# Generated by Django 5.1.11 on 2025-10-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "남성"),
                    ("female", "여성"),
                    ("undisclosed", "선택 안함"),
                ],
                help_text="성별 (남성/여성/선택 안함)",
                max_length=20,
                null=True,
            ),
        ),
    ]
