# Generated by Django - Data Migration
# Upgrade all VISITOR users to USER role

from django.db import migrations


def upgrade_visitor_to_user(apps, schema_editor):
    """기존 VISITOR 권한 사용자를 USER 권한으로 업그레이드"""
    User = apps.get_model('accounts', 'User')

    # VISITOR 사용자 수 확인
    visitor_count = User.objects.filter(role='visitor').count()
    print(f"\n업그레이드할 VISITOR 사용자: {visitor_count}명")

    # VISITOR → USER로 변경
    updated = User.objects.filter(role='visitor').update(role='user')
    print(f"업그레이드 완료: {updated}명의 사용자가 USER 권한으로 변경되었습니다.\n")


def downgrade_user_to_visitor(apps, schema_editor):
    """롤백: USER를 다시 VISITOR로 되돌림 (권장하지 않음)"""
    # 롤백은 일반적으로 권장하지 않지만, 필요시 수동으로 처리
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_gender'),
    ]

    operations = [
        migrations.RunPython(upgrade_visitor_to_user, downgrade_user_to_visitor),
    ]
