# Generated by Django 5.1.11 on 2025-10-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_upgrade_visitor_to_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="daily_match_count",
            field=models.IntegerField(default=0, help_text="2시간 내 매칭 횟수"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_match_reset",
            field=models.DateTimeField(
                auto_now_add=True, help_text="마지막 매칭 카운트 리셋 시각"
            ),
        ),
    ]
